### ISSUE TITLE
Add more than Top 1 for popular models.

### ISSUE THREAD

**Issue by tytech039** [db0/Simple-AI-Horde-Colab#9]
We have about ~80GB to work with here. Let's try to populate that with more models.

(Maybe up to top 5, or 10.)

**Comment by tazlin** [comment]
The issue is not disk space. At this moment, having multiple models in colab right now leads to a memory leak which will eventually cause a crash. As soon as it is possible, colab will likely default to more models.

**Comment by tytech039** [comment]
Alright, got that.
